### ISSUE TITLE
NEAR University Certificate Browser does not link to the right twitter account

### ISSUE THREAD

**Issue by jelilat** [NEAR-Edu/near-certification-tools#73]
NEAR University's new Twitter account is `@NEARUniversity`. However, the certificate's share button and the footer still mentions/links `@NEAREdu`

The `@NEAREdu` account does not exist. 

<img width="694" alt="Screenshot 2022-05-24 at 03 59 22" src="https://user-images.githubusercontent.com/23613565/169939957-dfb258af-e58c-48f2-9e14-56fcd589311d.png">

**Comment by jelilat** [comment]
A PR that solves this issue has been created here https://github.com/NEAR-Edu/near-certification-tools/pull/74

However, the NEAR team still needs to edit the Twitter link on the GitHub profile.

<img width="714" alt="Screenshot 2022-05-24 at 03 36 09" src="https://user-images.githubusercontent.com/23613565/169940062-6fb3c89a-25ea-4f43-a313-02ffce1feead.png">

**Comment by encody** [comment]
I've updated the GitHub profile. Thanks for pointing this out! 👍 

I think the PR looks fine but I'll wait for Ryan to approve it since I don't have the frontend set up for testing on this computer.

**Comment by sccheruku** [comment]
FWIW, This is the same profile that Airtable redirects folks after submitting a grant request.

**Comment by ryancwalsh** [comment]
@jelilat Thank you so much for this PR!

@encody Thanks for that fix.

@sccheruku Thanks; I saw today that Sherif said he fixed the redirect.
